-- MySQL Script generated by MySQL Workbench
-- Tue Jun 14 14:25:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `idcountry` INT NOT NULL AUTO_INCREMENT,
  `name_coun` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coach` (
  `idcoach` INT NOT NULL AUTO_INCREMENT,
  `surname_coach` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcoach`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`championship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`championship` (
  `idchampionship` INT NOT NULL AUTO_INCREMENT,
  `name_champ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idchampionship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`club` (
  `idclub` INT NOT NULL AUTO_INCREMENT,
  `name_club` VARCHAR(45) NOT NULL,
  `idcoach` INT NOT NULL,
  `id_champioship` INT NOT NULL,
  PRIMARY KEY (`idclub`),
  INDEX `coach_idx` (`idcoach` ASC) VISIBLE,
  INDEX `champioship_idx` (`id_champioship` ASC) VISIBLE,
  CONSTRAINT `coach`
    FOREIGN KEY (`idcoach`)
    REFERENCES `mydb`.`coach` (`idcoach`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `champioship`
    FOREIGN KEY (`id_champioship`)
    REFERENCES `mydb`.`championship` (`idchampionship`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player` (
  `idplayer` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `idclub` INT NOT NULL,
  `idcountry` INT NOT NULL,
  PRIMARY KEY (`idplayer`),
  INDEX `country_idx` (`idcountry` ASC) VISIBLE,
  INDEX `club_idx` (`idclub` ASC) VISIBLE,
  CONSTRAINT `country`
    FOREIGN KEY (`idcountry`)
    REFERENCES `mydb`.`country` (`idcountry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `club`
    FOREIGN KEY (`idclub`)
    REFERENCES `mydb`.`club` (`idclub`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`position` (
  `idposition` INT NOT NULL AUTO_INCREMENT,
  `name_pos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idposition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player/pos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player/pos` (
  `idplayer_pos` INT NOT NULL AUTO_INCREMENT,
  `idplayer` INT NOT NULL,
  `idposition` INT NOT NULL,
  PRIMARY KEY (`idplayer_pos`),
  INDEX `player_idx` (`idplayer` ASC) VISIBLE,
  INDEX `position_idx` (`idposition` ASC) VISIBLE,
  CONSTRAINT `player`
    FOREIGN KEY (`idplayer`)
    REFERENCES `mydb`.`player` (`idplayer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `position`
    FOREIGN KEY (`idposition`)
    REFERENCES `mydb`.`position` (`idposition`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
